services:
    _defaults:
        autowire: true
        autoconfigure: true

    Postyou\HeadlineTinyMceBundle\:
        resource: ../../
        exclude: ../../{ContaoManager,DependencyInjection,Resources}
